# Generated by Django 4.0.5 on 2022-06-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0002_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
