# Generated by Django 4.0.5 on 2022-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPage', '0003_alter_post_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
